/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.57).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.KeyCreated;
import io.swagger.model.ModelConfiguration;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.epos.dbconnector.Configuration;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-07-01T13:36:45.483299527Z[GMT]")
@Validated
public interface ShareApi {

    @Operation(summary = "Add configuration to database", description = "Add configuration to database", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Configuration not found"),
        
        @ApiResponse(responseCode = "422", description = "Validation exception") })
    @RequestMapping(value = "/share",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<KeyCreated> addConfiguration(@Parameter(in = ParameterIn.DEFAULT, description = "Configuration", required=true, schema=@Schema()) @Valid @RequestBody ModelConfiguration body
);


    @Operation(summary = "Retrieve configurations from database", description = "Retrieve configurations from database", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ModelConfiguration.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/share/{instance_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ModelConfiguration> findConfigurationsByID(@Parameter(in = ParameterIn.PATH, description = "Status values that need to be considered for filter", required=true, schema=@Schema()) @PathVariable("instance_id") String configuration
);

    @Operation(summary = "Retrieve configurations from database", description = "Retrieve configurations from database", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ModelConfiguration.class))),

            @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/share/all",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<Configuration>> findAllConfigurations();


    @Operation(summary = "Retrieve encrypted configuration from database", description = "Retrieve configuration from database and return it encrypted with AES", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ModelConfiguration.class))),
        @ApiResponse(responseCode = "404", description = "Configuration not found") })
    @RequestMapping(value = "/share/{instance_id}/encrypted",
        produces = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<ModelConfiguration> findConfigurationsByIDEncrypted(@Parameter(in = ParameterIn.PATH, description = "Configuration ID", required=true, schema=@Schema()) @PathVariable("instance_id") String configurationId);


    @Operation(summary = "Retrieve all configurations encrypted from database", description = "Retrieve all configurations from database and return them encrypted with AES", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ModelConfiguration.class)))),
            @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/share/all/encrypted",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<ModelConfiguration>> findAllConfigurationsEncrypted();


    @Operation(summary = "Update configuration in database", description = "Update an existing configuration in database", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ModelConfiguration.class))),
        @ApiResponse(responseCode = "404", description = "Configuration not found"),
        @ApiResponse(responseCode = "422", description = "Validation exception") })
    @RequestMapping(value = "/share/{instance_id}",
        consumes = { "application/json" },
        produces = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<ModelConfiguration> updateConfiguration(
        @Parameter(in = ParameterIn.PATH, description = "Configuration ID", required=true, schema=@Schema()) @PathVariable("instance_id") String configurationId,
        @Parameter(in = ParameterIn.DEFAULT, description = "Configuration", required=true, schema=@Schema()) @Valid @RequestBody ModelConfiguration body);


    @Operation(summary = "Delete configuration from database", description = "Delete a configuration from database by ID", tags={ "Configuration Sharing Service" })
    @ApiResponses(value = {
        @ApiResponse(responseCode = "204", description = "Successful operation - no content"),
        @ApiResponse(responseCode = "404", description = "Configuration not found") })
    @RequestMapping(value = "/share/{instance_id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteConfiguration(@Parameter(in = ParameterIn.PATH, description = "Configuration ID", required=true, schema=@Schema()) @PathVariable("instance_id") String configurationId);

}

